### ISSUE TITLE
Get-LocalizedDataRecursive: Fix localization strings

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Base#7]
This function has hardcoded strings in the code:

https://github.com/dsccommunity/DscResource.Base/blob/13e4e9d0eca514dfea7fd3b6f0767b322d3ce100/source/Private/Get-LocalizedDataRecursive.ps1#L76

https://github.com/dsccommunity/DscResource.Base/blob/13e4e9d0eca514dfea7fd3b6f0767b322d3ce100/source/Private/Get-LocalizedDataRecursive.ps1#L91

https://github.com/dsccommunity/DscResource.Base/blob/13e4e9d0eca514dfea7fd3b6f0767b322d3ce100/source/Private/Get-LocalizedDataRecursive.ps1#L110

They should be added as a localization string instead, in the file https://github.com/dsccommunity/DscResource.Base/blob/main/source/en-US/DscResource.Base.strings.psd1

Then used with `$script:localizedData.<StringKeyName>`

**Comment by johlju** [comment]
The tests should also be update so the same localization string is used.

**Comment by dan-hughes** [comment]
@johlju, I can work on this. 

I do not get tests passing though. It seems to be failing on some ```Write-Verbose``` calls.

Can you clone and see if the tests run?

**Comment by johlju** [comment]
This was a bug in `Get-LocalizedData` part of DscResource.Common. Scratched my head a while when I  debugged until I saw it returned boolean values in addition to the hashtable. Sent in PR https://github.com/dsccommunity/DscResource.Common/pull/123 to resolve it.

**Comment by johlju** [comment]
I pushed a new release of DscResource.Common so if you resolve dependencies again and do a rebuild the tests should now pass. Suggest removing the old version in `output/RequiredModules` just to be sure it is not used.
